# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: 🙌 Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # Currently only want to run every hour.. Don't know how much this would eat away at my 'free' compute time.
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: thaodt
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          committer_message: "Generated new metrics for Profile: ${filename}"
          committer_gist: "1db1d598a9e4550fa45eaede87135b3b"
          output_action: "gist"
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, about
          plugin_traffic: yes
