name: 🐍 Generate Snake Contribution GIF
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.gif
            assets/github-snake.svg?palette=github-dark
      # Commit the changes
      - name: Commit files
        run: |
          git config user.email "$(git log -n 1 --pretty=format:%an)" 
          git config user.name "$(git log -n 1 --pretty=format:%ae)"
          git add -A
          git commit -m ":snake: Updates Snake Contribution Animation"
          git push
